/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package my.edu.apu.views.panels;

/**
 *
 * @author pakdad
 */
public class SystemAdminView extends javax.swing.JPanel {

    /**
     * Creates new form SystemAdminView
     */
    public SystemAdminView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JLabel();
        txtDate = new javax.swing.JLabel();
        txtTime = new javax.swing.JLabel();
        txtTotalSupervisors = new javax.swing.JTextField();
        txtTotalStudents = new javax.swing.JTextField();
        txtTotalFacultyAdmin = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnQuickUserManagement = new javax.swing.JButton();
        btnQuickManageStudents = new javax.swing.JButton();
        btnQuickManageFacAdmins = new javax.swing.JButton();
        btnQuickManageSupervisors = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnQuickMonitorFailedLogins = new javax.swing.JButton();
        btnQuickAccount = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        txtUsername1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUserAccounts = new javax.swing.JTable();
        txtUsername2 = new javax.swing.JLabel();
        txtUsernameSearch = new javax.swing.JTextField();
        txtEmailSearch = new javax.swing.JTextField();
        btnResetSearch = new javax.swing.JButton();
        txtUsername3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txtUsername4 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtUserEmail = new javax.swing.JTextField();
        txtUsername5 = new javax.swing.JLabel();
        btnDeleteUser = new javax.swing.JButton();
        btnUpdateUserDetails = new javax.swing.JButton();
        comboAccStatusSearch = new javax.swing.JComboBox<>();
        txtUsername6 = new javax.swing.JLabel();
        comboUserAccStatus = new javax.swing.JComboBox<>();
        txtUsername7 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblStudentAccounts = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtStudentName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtStudentEmail = new javax.swing.JTextField();
        comboIntake = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        comboProgram = new javax.swing.JComboBox<>();
        btnUpdateStudent = new javax.swing.JButton();
        btnCreateStudent = new javax.swing.JButton();
        btnDeleteStudent = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        txtStudentPassword = new javax.swing.JPasswordField();
        jLabel29 = new javax.swing.JLabel();
        txtStudentDob = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblSupervisorAccounts = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        txtSupervisorName = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtSupervisorEmail = new javax.swing.JTextField();
        btnCreateSupervisor = new javax.swing.JButton();
        btnUpdateSupervisor = new javax.swing.JButton();
        btnDeleteSupervisor = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        txtSupervisorPassword = new javax.swing.JPasswordField();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblFacultyAdminAccounts = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtFacultyAdminName = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtFacultyAdminEmail = new javax.swing.JTextField();
        btnCreateFacultyAdmin = new javax.swing.JButton();
        btnUpdateFacultyAdmin = new javax.swing.JButton();
        btnDeleteFacultyAdmin = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        txtFacultyAdminPassword = new javax.swing.JPasswordField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblLoginAttempts = new javax.swing.JTable();
        txtUsername8 = new javax.swing.JLabel();
        txtUsername9 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblAggregatedAttempts = new javax.swing.JTable();
        btnClearLogs = new javax.swing.JButton();
        btnEnableAccount = new javax.swing.JButton();
        btnDisableAccount = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        btnSignOut = new javax.swing.JButton();

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        jLabel1.setText("Welcome Back,");

        txtUsername.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        txtUsername.setText("Rodrigo Mendez");

        txtDate.setText("6th September, 2025");

        txtTime.setText("4:00 PM");

        txtTotalSupervisors.setText("235");
        txtTotalSupervisors.setFocusable(false);

        txtTotalStudents.setText("1153");
        txtTotalStudents.setFocusable(false);
        txtTotalStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalStudentsActionPerformed(evt);
            }
        });

        txtTotalFacultyAdmin.setText("239");
        txtTotalFacultyAdmin.setFocusable(false);

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel5.setText("Total Students:");

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel6.setText("Total Supervisors:");

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel7.setText("Total Faculty Admins:");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnQuickUserManagement.setText("Manage Users");
        btnQuickUserManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuickUserManagementActionPerformed(evt);
            }
        });

        btnQuickManageStudents.setText("Manage Students");
        btnQuickManageStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuickManageStudentsActionPerformed(evt);
            }
        });

        btnQuickManageFacAdmins.setText("Manage Faculty Admins");
        btnQuickManageFacAdmins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuickManageFacAdminsActionPerformed(evt);
            }
        });

        btnQuickManageSupervisors.setText("Manage Supervisors");
        btnQuickManageSupervisors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuickManageSupervisorsActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel8.setText("Quick Actions:");

        btnQuickMonitorFailedLogins.setText("Monitor Failed Login Attempts");
        btnQuickMonitorFailedLogins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuickMonitorFailedLoginsActionPerformed(evt);
            }
        });

        btnQuickAccount.setText("Account");
        btnQuickAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuickAccountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtUsername))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDate, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTime, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(txtTotalSupervisors)
                            .addComponent(txtTotalStudents)
                            .addComponent(txtTotalFacultyAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnQuickManageSupervisors, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnQuickManageFacAdmins, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnQuickUserManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnQuickManageStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnQuickMonitorFailedLogins, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnQuickAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUsername))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtDate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTime)))
                .addGap(91, 91, 91)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtTotalStudents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTotalSupervisors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTotalFacultyAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnQuickUserManagement, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                                    .addComponent(btnQuickManageStudents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnQuickManageSupervisors, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                                    .addComponent(btnQuickManageFacAdmins, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnQuickMonitorFailedLogins, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnQuickAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 42, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Dashboard", jPanel1);

        txtUsername1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        txtUsername1.setText("Users:");

        tblUserAccounts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Jack", "jack@mail.apu.edu.my", "Student"},
                {"Chris", "chris@mail.apu.edu.my", "Student"},
                {"Cole", "cole@mail.apu.edu.my", "Student"},
                {"Tim", "tim@mail.apu.edu.my", "Student"},
                {"Bob", "bob@mail.apu.edu.my", "Supervisor"},
                {"Bill", "bill@mail.apu.edu.my", "Supervisor"},
                {"Mark", "mark@mail.apu.edu.my", "Faculty Admin"}
            },
            new String [] {
                "Name", "Email", "Role"
            }
        ));
        jScrollPane1.setViewportView(tblUserAccounts);
        if (tblUserAccounts.getColumnModel().getColumnCount() > 0) {
            tblUserAccounts.getColumnModel().getColumn(2).setHeaderValue("Intake");
        }

        txtUsername2.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        txtUsername2.setText("Search by Name:");

        btnResetSearch.setText("Reset Search");

        txtUsername3.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        txtUsername3.setText("Search by Email:");

        txtUsername4.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        txtUsername4.setText("Name:");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        txtUsername5.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        txtUsername5.setText("Email:");

        btnDeleteUser.setText("Delete User");

        btnUpdateUserDetails.setText("Update User");
        btnUpdateUserDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateUserDetailsActionPerformed(evt);
            }
        });

        comboAccStatusSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Enabled", "Disabled" }));
        comboAccStatusSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAccStatusSearchActionPerformed(evt);
            }
        });

        txtUsername6.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        txtUsername6.setText("Filter by Account Status:");

        comboUserAccStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---", "Enabled", "Disabled" }));

        txtUsername7.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        txtUsername7.setText("Account Status:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUsername1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUsernameSearch)
                    .addComponent(btnUpdateUserDetails, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                    .addComponent(btnDeleteUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtEmailSearch)
                    .addComponent(btnResetSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator2)
                    .addComponent(comboAccStatusSearch, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtUserEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtUsername2)
                    .addComponent(txtUsername3)
                    .addComponent(txtUsername6, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUsername4)
                    .addComponent(txtUsername5)
                    .addComponent(txtUsername7, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboUserAccStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsername1)
                    .addComponent(txtUsername2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(txtUsernameSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUsername3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmailSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUsername6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboAccStatusSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnResetSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(txtUsername4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtUsername5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUserEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUsername7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboUserAccStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUpdateUserDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jTabbedPane2.addTab("All Users", jPanel6);

        tblStudentAccounts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Jack", "jack@mail.apu.edu.my", "January", "Computer Science"},
                {"Chris", "chris@mail.apu.edu.my", "May", "Data Science"},
                {"Cole", "cole@mail.apu.edu.my", "September", "Software Engineering"},
                {"Tim", "tim@mail.apu.edu.my", "January", "Information Technology"},
                {"Bob", "bob@mail.apu.edu.my", "May", "Data Science"},
                {"Bill", "bill@mail.apu.edu.my", "January", "Data Science"},
                {"Mark", "mark@mail.apu.edu.my", "May", "Computer Technology"}
            },
            new String [] {
                "Name", "Email", "Intake", "Program"
            }
        ));
        jScrollPane2.setViewportView(tblStudentAccounts);
        if (tblStudentAccounts.getColumnModel().getColumnCount() > 0) {
            tblStudentAccounts.getColumnModel().getColumn(2).setHeaderValue("Intake");
            tblStudentAccounts.getColumnModel().getColumn(3).setResizable(false);
            tblStudentAccounts.getColumnModel().getColumn(3).setHeaderValue("Program");
        }

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel2.setText("Students:");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel3.setText("Name:");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel4.setText("Email:");

        comboIntake.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "May", "September" }));

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel9.setText("Intake:");

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel10.setText("Program:");

        comboProgram.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Computer Science", "Data Science", "Software Engineering", "Information Technology" }));

        btnUpdateStudent.setText("Update Student");

        btnCreateStudent.setText("Add Student");

        btnDeleteStudent.setText("Delete Student");

        jLabel23.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel23.setText("Password:");

        jLabel29.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel29.setText("DOB:");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtStudentName)
                    .addComponent(txtStudentEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                    .addComponent(btnUpdateStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCreateStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDeleteStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtStudentPassword)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboIntake, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(124, 124, 124))
                            .addComponent(comboProgram, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel23)
                            .addComponent(jLabel29))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtStudentDob, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(txtStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtStudentEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtStudentPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtStudentDob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboIntake, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboProgram, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCreateStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdateStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jTabbedPane2.addTab("Students", jPanel7);

        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel11.setText("Supervisors:");

        tblSupervisorAccounts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Jack", "jack@mail.apu.edu.my"},
                {"Chris", "chris@mail.apu.edu.my"},
                {"Cole", "cole@mail.apu.edu.my"},
                {"Tim", "tim@mail.apu.edu.my"},
                {"Bob", "bob@mail.apu.edu.my"},
                {"Bill", "bill@mail.apu.edu.my"},
                {"Mark", "mark@mail.apu.edu.my"}
            },
            new String [] {
                "Name", "Email"
            }
        ));
        jScrollPane3.setViewportView(tblSupervisorAccounts);

        jLabel12.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel12.setText("Name:");

        jLabel13.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel13.setText("Email:");

        txtSupervisorEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSupervisorEmailActionPerformed(evt);
            }
        });

        btnCreateSupervisor.setText("Create Supervisor");
        btnCreateSupervisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateSupervisorActionPerformed(evt);
            }
        });

        btnUpdateSupervisor.setText("Update Supervisor");

        btnDeleteSupervisor.setText("Delete Supervisor");

        jLabel24.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel24.setText("Password:");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSupervisorName)
                    .addComponent(btnCreateSupervisor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUpdateSupervisor, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                    .addComponent(btnDeleteSupervisor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSupervisorEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel24))
                        .addContainerGap())
                    .addComponent(txtSupervisorPassword)))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(txtSupervisorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSupervisorEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSupervisorPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCreateSupervisor, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdateSupervisor, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteSupervisor, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jTabbedPane2.addTab("Supervisors", jPanel8);

        tblFacultyAdminAccounts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Jack", "jack@mail.apu.edu.my"},
                {"Chris", "chris@mail.apu.edu.my"},
                {"Cole", "cole@mail.apu.edu.my"},
                {"Tim", "tim@mail.apu.edu.my"},
                {"Bob", "bob@mail.apu.edu.my"},
                {"Bill", "bill@mail.apu.edu.my"},
                {"Mark", "mark@mail.apu.edu.my"}
            },
            new String [] {
                "Name", "Email"
            }
        ));
        jScrollPane4.setViewportView(tblFacultyAdminAccounts);

        jLabel14.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel14.setText("Faculty Admin:");

        jLabel15.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel15.setText("Name:");

        jLabel16.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel16.setText("Email:");

        txtFacultyAdminEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFacultyAdminEmailActionPerformed(evt);
            }
        });

        btnCreateFacultyAdmin.setText("Create Faculty Admin");
        btnCreateFacultyAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateFacultyAdminActionPerformed(evt);
            }
        });

        btnUpdateFacultyAdmin.setText("Update Faculty Admin");

        btnDeleteFacultyAdmin.setText("Delete Faculty Admin");

        jLabel25.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel25.setText("Password:");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUpdateFacultyAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                    .addComponent(btnCreateFacultyAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtFacultyAdminName)
                    .addComponent(btnDeleteFacultyAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtFacultyAdminEmail)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtFacultyAdminPassword)))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFacultyAdminName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFacultyAdminEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFacultyAdminPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCreateFacultyAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdateFacultyAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteFacultyAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jTabbedPane2.addTab("Faculty Admin", jPanel9);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Manage Users", jPanel2);

        tblLoginAttempts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Email", "Failure Reason", "Timestamp"
            }
        ));
        tblLoginAttempts.setEnabled(false);
        jScrollPane5.setViewportView(tblLoginAttempts);

        txtUsername8.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        txtUsername8.setText("Aggregated Insights By Email:");

        txtUsername9.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        txtUsername9.setText("All Failed Login Attempts:");

        tblAggregatedAttempts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "Email", "Failed Attempts", "Last Attempt", "Account Status"
            }
        ));
        jScrollPane6.setViewportView(tblAggregatedAttempts);

        btnClearLogs.setText("Clear All Logs");

        btnEnableAccount.setText("Enable Account");

        btnDisableAccount.setText("Disable Account");
        btnDisableAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisableAccountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUsername8, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUsername9, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDisableAccount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                    .addComponent(btnEnableAccount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnClearLogs, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(txtUsername8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnEnableAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDisableAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(txtUsername9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClearLogs, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Monitor Failed Login Attempts", jPanel3);

        jLabel21.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel21.setText("Exit Your Account");

        jLabel22.setText("Leave your account and sign back in later to continue.");

        btnSignOut.setText("Sign out");
        btnSignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(325, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addComponent(btnSignOut, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(319, 319, 319))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addGap(35, 35, 35)
                .addComponent(btnSignOut, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(271, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Account", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignOutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSignOutActionPerformed

    private void btnCreateFacultyAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateFacultyAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCreateFacultyAdminActionPerformed

    private void txtFacultyAdminEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFacultyAdminEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFacultyAdminEmailActionPerformed

    private void btnCreateSupervisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateSupervisorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCreateSupervisorActionPerformed

    private void txtSupervisorEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSupervisorEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSupervisorEmailActionPerformed

    private void comboAccStatusSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAccStatusSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboAccStatusSearchActionPerformed

    private void btnUpdateUserDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateUserDetailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateUserDetailsActionPerformed

    private void btnQuickManageSupervisorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuickManageSupervisorsActionPerformed
        this.jTabbedPane1.setSelectedIndex(1);
        this.jTabbedPane2.setSelectedIndex(2);
    }//GEN-LAST:event_btnQuickManageSupervisorsActionPerformed

    private void btnQuickManageFacAdminsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuickManageFacAdminsActionPerformed
        this.jTabbedPane1.setSelectedIndex(1);
        this.jTabbedPane2.setSelectedIndex(3);
    }//GEN-LAST:event_btnQuickManageFacAdminsActionPerformed

    private void btnQuickManageStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuickManageStudentsActionPerformed
        this.jTabbedPane1.setSelectedIndex(1);
        this.jTabbedPane2.setSelectedIndex(1);
    }//GEN-LAST:event_btnQuickManageStudentsActionPerformed

    private void btnQuickUserManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuickUserManagementActionPerformed
        this.jTabbedPane1.setSelectedIndex(1);
        this.jTabbedPane2.setSelectedIndex(0);
    }//GEN-LAST:event_btnQuickUserManagementActionPerformed

    private void txtTotalStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalStudentsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalStudentsActionPerformed

    private void btnQuickMonitorFailedLoginsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuickMonitorFailedLoginsActionPerformed
        this.jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_btnQuickMonitorFailedLoginsActionPerformed

    private void btnQuickAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuickAccountActionPerformed
        this.jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_btnQuickAccountActionPerformed

    private void btnDisableAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisableAccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDisableAccountActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    public javax.swing.JTextField getTxtTotalStudents() {
        return this.txtTotalStudents;
    }

    public javax.swing.JTextField getTxtTotalSupervisors() {
        return this.txtTotalSupervisors;
    }

    public javax.swing.JTextField getTxtTotalFacultyAdmin() {
        return this.txtTotalFacultyAdmin;
    }

    public javax.swing.JLabel getTxtUsername() {
        return this.txtUsername;
    }

    public javax.swing.JLabel getTxtDate() {
        return this.txtDate;
    }

    public javax.swing.JLabel getTxtTime() {
        return this.txtTime;
    }

    public javax.swing.JTable getTblUserAccounts() {
        return this.tblUserAccounts;
    }

    public javax.swing.JTable getTblSupervisorAccounts() {
        return this.tblSupervisorAccounts;
    }

    public javax.swing.JButton getBtnUpdateUserDetails() {
        return this.btnUpdateUserDetails;
    }

    public javax.swing.JButton getBtnDeleteUser() {
        return this.btnDeleteUser;
    }

    public javax.swing.JTextField getTxtName() {
        return this.txtName;
    }

    public javax.swing.JTextField getTxtUserEmail() {
        return this.txtUserEmail;
    }

    public javax.swing.JTextField getTxtUsernameSearch() {
        return this.txtUsernameSearch;
    }

    public javax.swing.JTextField getTxtEmailSearch() {
        return this.txtEmailSearch;
    }

    public javax.swing.JTextField getTxtStudentName() {
        return this.txtStudentName;
    }

    public javax.swing.JTextField getTxtStudentEmail() {
        return this.txtStudentEmail;
    }

    public javax.swing.JTextField getTxtStudentDob() {
        return this.txtStudentDob;
    }

    public javax.swing.JTextField getTxtSupervisorName() {
        return this.txtSupervisorName;
    }

    public javax.swing.JTextField getTxtSupervisorEmail() {
        return this.txtSupervisorEmail;
    }

    public javax.swing.JTextField getTxtFacultyAdminName() {
        return this.txtFacultyAdminName;
    }

    public javax.swing.JTextField getTxtFacultyAdminEmail() {
        return this.txtFacultyAdminEmail;
    }

    public javax.swing.JPasswordField getTxtFacultyAdminPassword() {
        return this.txtFacultyAdminPassword;
    }

    public javax.swing.JPasswordField getTxtSupervisorPassword() {
        return this.txtSupervisorPassword;
    }

    public javax.swing.JPasswordField getTxtStudentPassword() {
        return this.txtStudentPassword;
    }

    public javax.swing.JButton getBtnResetSearch() {
        return this.btnResetSearch;
    }

    public javax.swing.JButton getBtnCreateFacultyAdmin() {
        return this.btnCreateFacultyAdmin;
    }

    public javax.swing.JButton getBtnUpdateFacultyAdmin() {
        return this.btnUpdateFacultyAdmin;
    }

    public javax.swing.JButton getBtnDeleteFacultyAdmin() {
        return this.btnDeleteFacultyAdmin;
    }

    public javax.swing.JButton getBtnDeleteStudent() {
        return this.btnDeleteStudent;
    }

    public javax.swing.JButton getBtnUpdateStudent() {
        return this.btnUpdateStudent;
    }

    public javax.swing.JButton getBtnCreateStudent() {
        return this.btnCreateStudent;
    }

    public javax.swing.JButton getBtnCreateSupervisor() {
        return this.btnCreateSupervisor;
    }

    public javax.swing.JButton getBtnUpdateSupervisor() {
        return this.btnUpdateSupervisor;
    }

    public javax.swing.JButton getBtnDeleteSupervisor() {
        return this.btnDeleteSupervisor;
    }

    public javax.swing.JButton getBtnEnableAccount() {
        return this.btnEnableAccount;
    }

    public javax.swing.JButton getBtnDisableAccount() {
        return this.btnDisableAccount;
    }

    public javax.swing.JButton getBtnClearLogs() {
        return this.btnClearLogs;
    }
    
    public javax.swing.JButton getBtnSignOut() {
        return this.btnSignOut;
    }

    public javax.swing.JTable getTblStudentAccounts() {
        return this.tblStudentAccounts;
    }

    public javax.swing.JTable getTblFacultyAdminAccounts() {
        return this.tblFacultyAdminAccounts;
    }

    public javax.swing.JTable getTblAggregatedAttempts() {
        return this.tblAggregatedAttempts;
    }

    public javax.swing.JTable getTblLoginAttempts() {
        return this.tblLoginAttempts;
    }

    public javax.swing.JComboBox getComboIntake() {
        return this.comboIntake;
    }

    public javax.swing.JComboBox getComboProgram() {
        return this.comboProgram;
    }

    public javax.swing.JComboBox getComboAccStatusSearch() {
        return this.comboAccStatusSearch;
    }

    public javax.swing.JComboBox getComboUserAccStatus() {
        return this.comboUserAccStatus;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClearLogs;
    private javax.swing.JButton btnCreateFacultyAdmin;
    private javax.swing.JButton btnCreateStudent;
    private javax.swing.JButton btnCreateSupervisor;
    private javax.swing.JButton btnDeleteFacultyAdmin;
    private javax.swing.JButton btnDeleteStudent;
    private javax.swing.JButton btnDeleteSupervisor;
    private javax.swing.JButton btnDeleteUser;
    private javax.swing.JButton btnDisableAccount;
    private javax.swing.JButton btnEnableAccount;
    private javax.swing.JButton btnQuickAccount;
    private javax.swing.JButton btnQuickManageFacAdmins;
    private javax.swing.JButton btnQuickManageStudents;
    private javax.swing.JButton btnQuickManageSupervisors;
    private javax.swing.JButton btnQuickMonitorFailedLogins;
    private javax.swing.JButton btnQuickUserManagement;
    private javax.swing.JButton btnResetSearch;
    private javax.swing.JButton btnSignOut;
    private javax.swing.JButton btnUpdateFacultyAdmin;
    private javax.swing.JButton btnUpdateStudent;
    private javax.swing.JButton btnUpdateSupervisor;
    private javax.swing.JButton btnUpdateUserDetails;
    private javax.swing.JComboBox<String> comboAccStatusSearch;
    private javax.swing.JComboBox<String> comboIntake;
    private javax.swing.JComboBox<String> comboProgram;
    private javax.swing.JComboBox<String> comboUserAccStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable tblAggregatedAttempts;
    private javax.swing.JTable tblFacultyAdminAccounts;
    private javax.swing.JTable tblLoginAttempts;
    private javax.swing.JTable tblStudentAccounts;
    private javax.swing.JTable tblSupervisorAccounts;
    private javax.swing.JTable tblUserAccounts;
    private javax.swing.JLabel txtDate;
    private javax.swing.JTextField txtEmailSearch;
    private javax.swing.JTextField txtFacultyAdminEmail;
    private javax.swing.JTextField txtFacultyAdminName;
    private javax.swing.JPasswordField txtFacultyAdminPassword;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtStudentDob;
    private javax.swing.JTextField txtStudentEmail;
    private javax.swing.JTextField txtStudentName;
    private javax.swing.JPasswordField txtStudentPassword;
    private javax.swing.JTextField txtSupervisorEmail;
    private javax.swing.JTextField txtSupervisorName;
    private javax.swing.JPasswordField txtSupervisorPassword;
    private javax.swing.JLabel txtTime;
    private javax.swing.JTextField txtTotalFacultyAdmin;
    private javax.swing.JTextField txtTotalStudents;
    private javax.swing.JTextField txtTotalSupervisors;
    private javax.swing.JTextField txtUserEmail;
    private javax.swing.JLabel txtUsername;
    private javax.swing.JLabel txtUsername1;
    private javax.swing.JLabel txtUsername2;
    private javax.swing.JLabel txtUsername3;
    private javax.swing.JLabel txtUsername4;
    private javax.swing.JLabel txtUsername5;
    private javax.swing.JLabel txtUsername6;
    private javax.swing.JLabel txtUsername7;
    private javax.swing.JLabel txtUsername8;
    private javax.swing.JLabel txtUsername9;
    private javax.swing.JTextField txtUsernameSearch;
    // End of variables declaration//GEN-END:variables
}
